// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: panacea/status/v0/status.proto

package v0

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_panacea_status_v0_status_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panacea_status_v0_status_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_panacea_status_v0_status_proto_rawDescGZIP(), []int{0}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OracleAccountAddress string             `protobuf:"bytes,1,opt,name=oracle_account_address,proto3" json:"oracle_account_address,omitempty"`
	Api                  *StatusAPI         `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	Grpc                 *StatusGRPC        `protobuf:"bytes,3,opt,name=grpc,proto3" json:"grpc,omitempty"`
	EnclaveInfo          *StatusEnclaveInfo `protobuf:"bytes,4,opt,name=enclave_info,proto3" json:"enclave_info,omitempty"`
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_panacea_status_v0_status_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panacea_status_v0_status_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_panacea_status_v0_status_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusResponse) GetOracleAccountAddress() string {
	if x != nil {
		return x.OracleAccountAddress
	}
	return ""
}

func (x *GetStatusResponse) GetApi() *StatusAPI {
	if x != nil {
		return x.Api
	}
	return nil
}

func (x *GetStatusResponse) GetGrpc() *StatusGRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *GetStatusResponse) GetEnclaveInfo() *StatusEnclaveInfo {
	if x != nil {
		return x.EnclaveInfo
	}
	return nil
}

type StatusAPI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled    bool   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ListenAddr string `protobuf:"bytes,2,opt,name=listen_addr,proto3" json:"listen_addr,omitempty"`
}

func (x *StatusAPI) Reset() {
	*x = StatusAPI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_panacea_status_v0_status_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusAPI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusAPI) ProtoMessage() {}

func (x *StatusAPI) ProtoReflect() protoreflect.Message {
	mi := &file_panacea_status_v0_status_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusAPI.ProtoReflect.Descriptor instead.
func (*StatusAPI) Descriptor() ([]byte, []int) {
	return file_panacea_status_v0_status_proto_rawDescGZIP(), []int{2}
}

func (x *StatusAPI) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *StatusAPI) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

type StatusGRPC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled    bool   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ListenAddr string `protobuf:"bytes,2,opt,name=listen_addr,proto3" json:"listen_addr,omitempty"`
}

func (x *StatusGRPC) Reset() {
	*x = StatusGRPC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_panacea_status_v0_status_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusGRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusGRPC) ProtoMessage() {}

func (x *StatusGRPC) ProtoReflect() protoreflect.Message {
	mi := &file_panacea_status_v0_status_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusGRPC.ProtoReflect.Descriptor instead.
func (*StatusGRPC) Descriptor() ([]byte, []int) {
	return file_panacea_status_v0_status_proto_rawDescGZIP(), []int{3}
}

func (x *StatusGRPC) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *StatusGRPC) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

type StatusEnclaveInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId []byte `protobuf:"bytes,1,opt,name=product_id,proto3" json:"product_id,omitempty"`
	UniqueId  string `protobuf:"bytes,2,opt,name=unique_id,proto3" json:"unique_id,omitempty"`
}

func (x *StatusEnclaveInfo) Reset() {
	*x = StatusEnclaveInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_panacea_status_v0_status_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusEnclaveInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusEnclaveInfo) ProtoMessage() {}

func (x *StatusEnclaveInfo) ProtoReflect() protoreflect.Message {
	mi := &file_panacea_status_v0_status_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusEnclaveInfo.ProtoReflect.Descriptor instead.
func (*StatusEnclaveInfo) Descriptor() ([]byte, []int) {
	return file_panacea_status_v0_status_proto_rawDescGZIP(), []int{4}
}

func (x *StatusEnclaveInfo) GetProductId() []byte {
	if x != nil {
		return x.ProductId
	}
	return nil
}

func (x *StatusEnclaveInfo) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

var File_panacea_status_v0_status_proto protoreflect.FileDescriptor

var file_panacea_status_v0_status_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x61, 0x6e, 0x61, 0x63, 0x65, 0x61, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x2f, 0x76, 0x30, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x18, 0x70, 0x61, 0x6e, 0x61, 0x63, 0x65, 0x61, 0x5f, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65,
	0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x76, 0x30, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x8d, 0x02, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x36, 0x0a, 0x16, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x5f, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x16, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x35, 0x0a, 0x03, 0x61, 0x70,
	0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x61, 0x6e, 0x61, 0x63, 0x65,
	0x61, 0x5f, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e,
	0x76, 0x30, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x41, 0x50, 0x49, 0x52, 0x03, 0x61, 0x70,
	0x69, 0x12, 0x38, 0x0a, 0x04, 0x67, 0x72, 0x70, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x24, 0x2e, 0x70, 0x61, 0x6e, 0x61, 0x63, 0x65, 0x61, 0x5f, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65,
	0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x76, 0x30, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x47, 0x52, 0x50, 0x43, 0x52, 0x04, 0x67, 0x72, 0x70, 0x63, 0x12, 0x4f, 0x0a, 0x0c, 0x65,
	0x6e, 0x63, 0x6c, 0x61, 0x76, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2b, 0x2e, 0x70, 0x61, 0x6e, 0x61, 0x63, 0x65, 0x61, 0x5f, 0x6f, 0x72, 0x61, 0x63,
	0x6c, 0x65, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x76, 0x30, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x45, 0x6e, 0x63, 0x6c, 0x61, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c,
	0x65, 0x6e, 0x63, 0x6c, 0x61, 0x76, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x47, 0x0a, 0x09,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x41, 0x50, 0x49, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x22, 0x48, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x47,
	0x52, 0x50, 0x43, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x20, 0x0a,
	0x0b, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x22,
	0x51, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x6e, 0x63, 0x6c, 0x61, 0x76, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x5f, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f,
	0x69, 0x64, 0x32, 0x89, 0x01, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x78, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x2a, 0x2e, 0x70, 0x61, 0x6e, 0x61, 0x63, 0x65, 0x61, 0x5f, 0x6f, 0x72, 0x61, 0x63,
	0x6c, 0x65, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e,
	0x70, 0x61, 0x6e, 0x61, 0x63, 0x65, 0x61, 0x5f, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x2e, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x12, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x0c, 0x12, 0x0a, 0x2f, 0x76, 0x30, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x31,
	0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x64,
	0x69, 0x62, 0x6c, 0x6f, 0x63, 0x2f, 0x70, 0x61, 0x6e, 0x61, 0x63, 0x65, 0x61, 0x2d, 0x6f, 0x72,
	0x61, 0x63, 0x6c, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2f, 0x76,
	0x30, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_panacea_status_v0_status_proto_rawDescOnce sync.Once
	file_panacea_status_v0_status_proto_rawDescData = file_panacea_status_v0_status_proto_rawDesc
)

func file_panacea_status_v0_status_proto_rawDescGZIP() []byte {
	file_panacea_status_v0_status_proto_rawDescOnce.Do(func() {
		file_panacea_status_v0_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_panacea_status_v0_status_proto_rawDescData)
	})
	return file_panacea_status_v0_status_proto_rawDescData
}

var file_panacea_status_v0_status_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_panacea_status_v0_status_proto_goTypes = []interface{}{
	(*GetStatusRequest)(nil),  // 0: panacea_oracle.status.v0.GetStatusRequest
	(*GetStatusResponse)(nil), // 1: panacea_oracle.status.v0.GetStatusResponse
	(*StatusAPI)(nil),         // 2: panacea_oracle.status.v0.StatusAPI
	(*StatusGRPC)(nil),        // 3: panacea_oracle.status.v0.StatusGRPC
	(*StatusEnclaveInfo)(nil), // 4: panacea_oracle.status.v0.StatusEnclaveInfo
}
var file_panacea_status_v0_status_proto_depIdxs = []int32{
	2, // 0: panacea_oracle.status.v0.GetStatusResponse.api:type_name -> panacea_oracle.status.v0.StatusAPI
	3, // 1: panacea_oracle.status.v0.GetStatusResponse.grpc:type_name -> panacea_oracle.status.v0.StatusGRPC
	4, // 2: panacea_oracle.status.v0.GetStatusResponse.enclave_info:type_name -> panacea_oracle.status.v0.StatusEnclaveInfo
	0, // 3: panacea_oracle.status.v0.StatusService.GetStatus:input_type -> panacea_oracle.status.v0.GetStatusRequest
	1, // 4: panacea_oracle.status.v0.StatusService.GetStatus:output_type -> panacea_oracle.status.v0.GetStatusResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_panacea_status_v0_status_proto_init() }
func file_panacea_status_v0_status_proto_init() {
	if File_panacea_status_v0_status_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_panacea_status_v0_status_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_panacea_status_v0_status_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_panacea_status_v0_status_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusAPI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_panacea_status_v0_status_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusGRPC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_panacea_status_v0_status_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusEnclaveInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_panacea_status_v0_status_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_panacea_status_v0_status_proto_goTypes,
		DependencyIndexes: file_panacea_status_v0_status_proto_depIdxs,
		MessageInfos:      file_panacea_status_v0_status_proto_msgTypes,
	}.Build()
	File_panacea_status_v0_status_proto = out.File
	file_panacea_status_v0_status_proto_rawDesc = nil
	file_panacea_status_v0_status_proto_goTypes = nil
	file_panacea_status_v0_status_proto_depIdxs = nil
}
